import type { Difficulty, SimulationSettings } from './types';

export const defaultSettings: SimulationSettings = {
  difficulty: 'normal',
  fishCount: 520,
  fishSpecies: 'sardine',
  schoolMode: 'auto',
  speed: 68,
  maxForce: 205,
  separationWeight: 1.65,
  alignmentWeight: 1.08,
  cohesionWeight: 0.78,
  predatorRadius: 210,
  predatorStrength: 560,
  biteRadius: 36,
  biteKillSpeedThreshold: 132,
  biteKillCompanionThreshold: 6,
  missSpawnCount: 8,
  penaltyEnabled: true,
  penaltyContactRadius: 18,
  penaltyContactCount: 8,
  penaltyCost: 6,
  penaltySpeedThreshold: 1100,
  penaltyDwellSeconds: 1.45,
  blackHoleEnabled: false,
  blackHoleRadius: 92,
  blackHolePullStrength: 760,
  blackHoleKillRadius: 18,
  scatterEnabled: false,
  scatterRadius: 150,
  scatterStrength: 360,
  decoyEnabled: false,
  decoyRadius: 175,
  decoyStrength: 470,
  decoyLifetime: 8,
  showPredatorRadius: false,
  showBiteRadius: true,
  showVelocityVectors: false,
  showFps: true,
  separationRadius: 18,
  alignmentRadius: 48,
  cohesionRadius: 94,
  boundaryMargin: 150,
  boundaryStrength: 520,
};

export const difficultyPresets: Record<Difficulty, Partial<SimulationSettings>> = {
  easy: {
    difficulty: 'easy',
    fishCount: 300,
    predatorRadius: 230,
    predatorStrength: 620,
    biteRadius: 46,
    biteKillSpeedThreshold: 145,
    biteKillCompanionThreshold: 9,
    missSpawnCount: 4,
    penaltyCost: 3,
    penaltyContactCount: 9,
    penaltyDwellSeconds: 1.7,
    speed: 62,
    maxForce: 220,
    cohesionWeight: 0.7,
  },
  normal: {
    difficulty: 'normal',
    fishCount: 520,
    predatorRadius: 210,
    predatorStrength: 560,
    biteRadius: 36,
    biteKillSpeedThreshold: 132,
    biteKillCompanionThreshold: 6,
    missSpawnCount: 8,
    penaltyCost: 6,
    penaltyContactCount: 8,
    penaltyDwellSeconds: 1.45,
    speed: 68,
    maxForce: 205,
    cohesionWeight: 0.78,
  },
  hard: {
    difficulty: 'hard',
    fishCount: 760,
    predatorRadius: 190,
    predatorStrength: 500,
    biteRadius: 28,
    biteKillSpeedThreshold: 116,
    biteKillCompanionThreshold: 4,
    missSpawnCount: 14,
    penaltyCost: 10,
    penaltyContactCount: 7,
    penaltyDwellSeconds: 1.2,
    speed: 76,
    maxForce: 230,
    alignmentWeight: 1.22,
    cohesionWeight: 0.92,
  },
};
